services:
  postgres:
    image: postgres:16
    restart: always
    container_name: cafe_db_container
    environment:
      POSTGRES_DB: cafedb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  api:
    build:
      context: .
      dockerfile: CafeApi/Dockerfile
    ports:
      - "5285:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=cafedb;Username=${DB_USER};Password=${DB_PASSWORD}
    
volumes:
  postgres_data:
    
    