services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: cafedb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: